# Generated by Django 6.0.1 on 2026-02-04 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_conversation_agent_alter_conversation_client_and_more'),
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='visits.visit'),
        ),
    ]
