# Generated by Django 6.0.1 on 2026-01-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_avenue_property_commune_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('Vente', 'Vente'), ('Location', 'Location')], default='rent', max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('Maison', 'Maison'), ('apartment', 'Appartement'), ('Terrain', 'Terrain'), ('commercial', 'Commercial')], max_length=20),
        ),
    ]
