# Generated by Django 6.0.1 on 2026-01-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_listing_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('Vente', 'Vente'), ('Location', 'Location')], default='Location', max_length=10),
        ),
    ]
