# Generated by Django 6.0.1 on 2026-01-27 18:18

from django.db import migrations, models
from django.utils.text import slugify

def populate_slugs(apps, schema_editor):
    Property = apps.get_model('properties', 'Property')
    for property in Property.objects.all():
        if not property.slug:
            base_slug = slugify(property.title)
            slug = base_slug
            counter = 1
            # Check against existing slugs to ensure uniqueness
            while Property.objects.filter(slug=slug).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            property.slug = slug
            property.save()

class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_property_listing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.RunPython(populate_slugs),
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
