# Generated by Django 6.0.1 on 2026-01-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_property_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
