# Generated by Django 6.0.1 on 2026-02-04 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_visit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
